"""Deterministic rule checks for the conformance flow.

This package replaces the former single-file deterministic.py. The
public surface is preserved: every name that used to be importable
as `from evaluator_cog.engine.deterministic import X` is re-exported
from here unchanged.
"""

from __future__ import annotations

from evaluator_cog.engine.deterministic._shared import (
    CheckResult,
    Finding,
    _finding,
)
from evaluator_cog.engine.deterministic.api import (
    check_async_sqlalchemy,
    check_cors_config,
    check_db_writes_use_upserts,
    check_fetch_error_handling,
    check_health_endpoint,
    check_inputs_not_deleted,
    check_orm_usage,
    check_owner_id_column,
    check_postgres_only_data_store,
    check_pydantic_for_external_data,
    check_railway_hosted_api,
    check_response_envelope_presence,
    check_response_shape_parity,
    check_v1_route_prefix,
)
from evaluator_cog.engine.deterministic.auth import (
    check_auth_header_parity,
    check_clerk_auth_dep,
    check_unauthenticated_routes,
)
from evaluator_cog.engine.deterministic.config import (
    check_env_example_settings_parity,
    check_env_var_prefix,
    check_hardcoded_standards_version,
    check_hardcoded_time_values,
    check_logger_misuse,
    check_settings_field_consistency,
    check_shared_library_used,
    check_standards_freshness,
)
from evaluator_cog.engine.deterministic.containers import (
    check_cd_017,
    check_cd_021,
    check_cd_022,
    check_cd_023,
    check_cd_024,
)
from evaluator_cog.engine.deterministic.crossrepo import (
    check_xstack_006,
    check_xstack_007,
)
from evaluator_cog.engine.deterministic.delivery import (
    check_ci,
    check_gha_not_trigger_relay,
    check_migration_in_ci,
    check_no_hardcoded_secrets,
    check_no_hardcoded_urls,
    check_no_print_statements,
    check_pnpm_lockfile,
    check_pytest_coverage_in_ci,
    check_structured_logging,
    check_three_layer_observability,
)
from evaluator_cog.engine.deterministic.docs import (
    check_adrs_present,
    check_changelog,
    check_env_example,
    check_fastapi_route_docs,
    check_public_docstrings,
    check_pydantic_field_descriptions,
    check_readme,
    check_readme_running_locally,
    check_split_package_identity,
    check_unauthenticated_routes_documented,
)
from evaluator_cog.engine.deterministic.frontend import (
    check_astro_build_time_data,
    check_astro_framework,
    check_astro_pinned_versions,
    check_astro_runtime_queries,
    check_cloudflare_pages_deploy,
    check_react_hook_form_zod,
    check_shadcn,
    check_tailwind,
    check_vite_react_ts,
)
from evaluator_cog.engine.deterministic.identity import (
    check_auth_003,
    check_auth_004,
    check_cd_019,
)
from evaluator_cog.engine.deterministic.introspection import (
    check_eval_003,
    check_eval_007,
    check_mono_003,
)
from evaluator_cog.engine.deterministic.meta import (
    check_meta_005_check_notes_prefix,
    check_meta_006_prefix_file_correlation,
    check_meta_007_rule_ids_unique,
    check_meta_canonical_enums_are_dicts,
    check_meta_no_scattered_metadata,
    check_meta_release_pipeline_wired,
)
from evaluator_cog.engine.deterministic.operations import (
    check_ops_001,
    check_ops_002,
    check_ops_003,
    check_ops_004,
    check_ops_005,
    check_ops_006,
)
from evaluator_cog.engine.deterministic.packaging import (
    check_cd_016,
    check_cd_020,
)
from evaluator_cog.engine.deterministic.pipeline import (
    check_evaluation_step,
    check_final_evaluation_task,
    check_hardcoded_retry_delay,
    check_healthchecks_integration,
    check_no_retired_trigger_patterns,
    check_prefect_cloud_observability,
    check_prefect_present,
    check_prefect_run_logger,
    check_prefect_serve_pattern,
    check_retry_logic,
    check_shared_resource_concurrency,
)
from evaluator_cog.engine.deterministic.python import (
    check_common_python_utils_dep,
    check_dedup_handling_present,
    check_failed_prefix,
    check_finally_cleanup,
    check_mypy_in_ci,
    check_naming_conventions,
    check_no_setup_py,
    check_pre_commit,
    check_pyproject,
    check_src_layout,
)
from evaluator_cog.engine.deterministic.runner import (
    _deduplicate_same_repo_findings,
    _type_to_dod,
    run_all_checks,
)
from evaluator_cog.engine.deterministic.security import (
    check_sec_001,
    check_sec_002,
    check_sec_003,
    check_sec_004,
    check_sec_005,
    check_sec_006,
)
from evaluator_cog.engine.deterministic.testing import (
    check_db_test_fixtures,
    check_mock_assertions,
    check_pytest_config,
    check_respx_for_http_mocking,
    check_route_contract_tests,
    check_test_gap_critical_paths,
    check_testclient_for_v1_routes,
)
from evaluator_cog.engine.deterministic.versioning import (
    check_breaking_change_footer,
    check_conventional_commits,
    check_no_manual_changelog,
    check_releaserc,
    check_releaserc_assets,
)

__all__ = [
    "check_auth_003",
    "check_auth_004",
    "check_cd_016",
    "check_cd_017",
    "check_cd_019",
    "check_cd_020",
    "check_cd_021",
    "check_cd_022",
    "check_cd_023",
    "check_cd_024",
    "check_ops_001",
    "check_ops_002",
    "check_ops_003",
    "check_ops_004",
    "check_ops_005",
    "check_ops_006",
    "check_sec_001",
    "check_sec_002",
    "check_sec_003",
    "check_sec_004",
    "check_sec_005",
    "check_sec_006",
    "check_xstack_006",
    "check_xstack_007",
    "CheckResult",
    "Finding",
    "_deduplicate_same_repo_findings",
    "_finding",
    "_type_to_dod",
    "check_adrs_present",
    "check_astro_build_time_data",
    "check_astro_framework",
    "check_astro_pinned_versions",
    "check_astro_runtime_queries",
    "check_async_sqlalchemy",
    "check_auth_header_parity",
    "check_breaking_change_footer",
    "check_changelog",
    "check_ci",
    "check_clerk_auth_dep",
    "check_cloudflare_pages_deploy",
    "check_common_python_utils_dep",
    "check_conventional_commits",
    "check_cors_config",
    "check_db_test_fixtures",
    "check_db_writes_use_upserts",
    "check_dedup_handling_present",
    "check_env_example",
    "check_env_example_settings_parity",
    "check_env_var_prefix",
    "check_eval_003",
    "check_eval_007",
    "check_evaluation_step",
    "check_failed_prefix",
    "check_fastapi_route_docs",
    "check_fetch_error_handling",
    "check_final_evaluation_task",
    "check_finally_cleanup",
    "check_gha_not_trigger_relay",
    "check_hardcoded_retry_delay",
    "check_hardcoded_standards_version",
    "check_hardcoded_time_values",
    "check_health_endpoint",
    "check_healthchecks_integration",
    "check_inputs_not_deleted",
    "check_logger_misuse",
    "check_meta_005_check_notes_prefix",
    "check_meta_006_prefix_file_correlation",
    "check_meta_007_rule_ids_unique",
    "check_meta_canonical_enums_are_dicts",
    "check_meta_no_scattered_metadata",
    "check_meta_release_pipeline_wired",
    "check_migration_in_ci",
    "check_mock_assertions",
    "check_mono_003",
    "check_mypy_in_ci",
    "check_naming_conventions",
    "check_no_hardcoded_secrets",
    "check_no_hardcoded_urls",
    "check_no_manual_changelog",
    "check_no_print_statements",
    "check_no_retired_trigger_patterns",
    "check_no_setup_py",
    "check_orm_usage",
    "check_owner_id_column",
    "check_pnpm_lockfile",
    "check_postgres_only_data_store",
    "check_pre_commit",
    "check_prefect_cloud_observability",
    "check_prefect_present",
    "check_prefect_run_logger",
    "check_prefect_serve_pattern",
    "check_public_docstrings",
    "check_pydantic_field_descriptions",
    "check_pydantic_for_external_data",
    "check_pyproject",
    "check_pytest_config",
    "check_pytest_coverage_in_ci",
    "check_railway_hosted_api",
    "check_react_hook_form_zod",
    "check_readme",
    "check_readme_running_locally",
    "check_releaserc",
    "check_releaserc_assets",
    "check_response_envelope_presence",
    "check_response_shape_parity",
    "check_respx_for_http_mocking",
    "check_retry_logic",
    "check_route_contract_tests",
    "check_settings_field_consistency",
    "check_shadcn",
    "check_shared_library_used",
    "check_shared_resource_concurrency",
    "check_split_package_identity",
    "check_src_layout",
    "check_standards_freshness",
    "check_structured_logging",
    "check_tailwind",
    "check_test_gap_critical_paths",
    "check_testclient_for_v1_routes",
    "check_three_layer_observability",
    "check_unauthenticated_routes",
    "check_unauthenticated_routes_documented",
    "check_v1_route_prefix",
    "check_vite_react_ts",
    "run_all_checks",
]
